# Extracted from the stock firmware
interface=wlan0
bridge=br0
driver=nl80211

# SSID
ssid=4G-UFI-910
hw_mode=g
channel=1
ieee80211n=1
ht_capab=[SHORT-GI-20]
beacon_int=100

# Password
wpa=2
wpa_passphrase=1234567890
rsn_pairwise=CCMP
wpa_group_rekey=86400

dtim_period=2
max_num_sta=10
auth_algs=3
ignore_broadcast_ssid=0
wmm_enabled=1
